{% set name = "cssselect" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cbe82dd7acbee9ba9e5723b5f9e4749826912f1fb31cd7f92aabed5fde15b15

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.27.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cssselect
  requires:
    - pip
    - pytest
    # Not in main channel
    - lxml  # [not (win and arm64)]
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://pythonhosted.org/cssselect
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: CSS Selectors for Python
  description: |
    Cssselect parses CSS3 Selectors and translate them to XPath 1.0
    expressions. Such expressions can be used in lxml or another XPath engine
    to find the matching elements in an XML or HTML document.
  doc_url: https://cssselect.readthedocs.io
  dev_url: https://github.com/scrapy/cssselect

extra:
  recipe-maintainers:
    - vamega
