{% set name = "cssselect" %}
{% set version = "1.2.0" %}
{% set sha256 = "a5d17fc420dad4d70ff63a585ad315caf9c5868f750551362b5dbb6e8307c66c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scrapy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  imports:
    - cssselect
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pythonhosted.org/cssselect/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: CSS Selectors for Python
  description: |
    Cssselect parses CSS3 Selectors and translate them to XPath 1.0
    expressions. Such expressions can be used in lxml or another XPath engine
    to find the matching elements in an XML or HTML document.
  doc_url: https://cssselect.readthedocs.io/
  dev_url: https://github.com/scrapy/cssselect

extra:
  recipe-maintainers:
    - vamega
