{% set name = "cssselect" %}
{% set version = "1.0.0" %}
{% set sha256 = "582a85780249255707872c31d0438fc457aa24cfb43e472ff8f3e7ad6857953f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scrapy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cssselect

about:
  home: https://pythonhosted.org/cssselect/
  license: BSD3
  summary: CSS Selectors for Python

extra:
  recipe-maintainers:
    - vamega
