travis:
  secure:
    BINSTAR_TOKEN: n2v7zd7GTLdR0iJ2nMKg5SGW01Vcx0Sji/ebvoiynznROC15YIQLa0sJjTWCUBz1YcCOc5JgpWtC72KfzVtSXjrIvVZvW6ewi+OWXAH4Z2mPo7vJB/5ycvtKrLdRLssIvsCgdoK/9UcmEZ5Db2ly4wKOYxD6hCjDzgvSYScmrW5CA5eBFgBBBfTWfn7DMHi2GlbmBfddNe0rdwpvAdXn11VHjFb9Rf673Uu7/0qeLplqJ6DqC/pYTUXR+HdLEn/yOd5bjp5QN7Qojlt0A6yJK9u8uEDF4JWhd2uruPmUN8DjdrD4WaJEQeZMBhaTIQCbtfasNz5mL7l0gcPNixv4yqi4RDf+o3bOxyfQDmSuL+55rGJSILh2e9TVB5YRSGf5KpJYQkCAVwPYEC7C7zmTASKQmDO7yOxPhiUrDxT/L/dpjswPCxRptulqsUHglS1XNUshsfuO9Vsk6hrigFWhmbN1ndpBam6rTsCwven08/h/Vs31+4rMmg+GMOoR863XSpG9Yhi1hE8IYljOTnotf/0ZpRVpfVdHihvs6wTfMFhOcrkYtNUc9UXbRXo0gqHygsaQsu3ItgbYVtfB1U8w3qBI9MfFdPA4XqzQnOl2FMN49PKq1daBFUeTebkLQbfIP+6KPZvxnTzkGuExaJYEciPtTDfo+HDcHtHY2HS1trg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
