travis:
  secure:
    BINSTAR_TOKEN: jHYKY0XgGCnuIzAalNmSm/4TaclqgYnsF/Cxw3xm+i+hP7AsTxDNfbM2fI8Zrqe1OEEq62AwM/xXj2qygUCMW2xNwrR3yH6VY+FBuqh9J5uRJsSgpOw6UEFfpLtYDAVAiZbjl+X34YhFY3cW+Snodhz6oszW4c3m6hXB5FB+VZEEdAThoY/7DnMka15Ii/MmNN/x7ohiwjRT5VRVRGBIhlC9FNIK3+sQ+SHlVveXc/iBRqqCts2sR6szD6CW5Ig88HhzZOB9de3OrxmKu//iC/8wbWlSYoiXvhWEMV50S6jS+4jXCwXODnJ/NTOYFofuptLZp5AnmbXs/AXSCanXOOtrPt8fEXoYDYwHbIh2fWavCMGqTwi19sgMwXbluOUtB1zSOGgpXEdmeM0khtB1xZQ4OpwyCRFabBHMw8n4lydeNR8ToUchIebhsc0KjmBwNNekvVtUz3eJDEVuPOZwUNOXXAin0SlBykKDNqCILr/R98Pwjaw6Q7B//ozbY75yQgF1abaUSkQFODmyIwkOTnmnANMJ8FW0NQMSP6adnfGYPQ/Leqc/q1h5Fd1UKV6i5WqrlawqDB0Pa0T7jIbCN9rmEsYo/5kIwgwze4z+AKdn0SijeHiOGpXVpkkFTXZdY6l9dW6ScX8fpmF5uyYv536X+L6aKGNAIQZxtp5xwqY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
