travis:
  secure:
    BINSTAR_TOKEN: mJDbjziGr8Bb2pJsIiQJOBOT6vGX6IFQ1QLnzKsCOTm4lCy83lMmC5jiMMNJlcbUZv34rjGeTIakcx8YzEYEvakTxIU7LWJMtkZwc7vARAz/yhFlJ4fnWp71AzSdpLt3BuzP4WjVUBaC19HJHaTsHJJClE8rOs/O3CfdKLyt3VhrThfJScHLakwzX5WfMDHysJlpOCSzWLXI3SOtrtQ5DRGJwppPlXiWjDRd9gKVLvy814T3IHqf0qoxrQlgsupGYPegY11S2dUbPJWrLPqWpsiSBVSfr1xWygyk504WrKU9Lr6EFCO8bAJSTE0rdmsfiZChole5aGJ/xEVViJNq9eZ0P7hfjp4CYY7yb5rb11GlT4JT0pKcnRAPPkq0ZbIdSe/tnPqtERFileahyx+UCUjTbn3zNvmjy7ehnFIv4RpT0bVoDG45FDQkxTgpdhDHOvPfQpuZJK/WdMMuSkysElnTiEX5UrytmKI9d2I4Elsx+XWk8MqmboHvyW/ZW4ydoll/IY5J2Z54pZiCnbUfUjJopDXvS9h2YnYSX2Wzk74TQ6SGUbp9rMjd/2z8Td/3s4+SzpOCmpVlAT+xQX602Ceu+Ns/S25Mut5NrpoCGt4vzYETY4tdk1nNaktOKMGVUrSZlp4pI8jDn8n6nyskI/VihxRlFT9sofhUgBrx3TI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
